// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoyA5GpUoVVi1VBkVda-TIlcytjNrqX6Q',
    appId: '1:951154714575:web:a2a6b348c70a2df77294ba',
    messagingSenderId: '951154714575',
    projectId: 'nguoi-di-rung',
    authDomain: 'nguoi-di-rung.firebaseapp.com',
    databaseURL: 'https://nguoi-di-rung-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nguoi-di-rung.firebasestorage.app',
    measurementId: 'G-XZ48Q5E9SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKXX1s0yBaz8Z1TAlvE6RXkRy9xSJJznA',
    appId: '1:951154714575:android:edf0c51b194bd64c7294ba',
    messagingSenderId: '951154714575',
    projectId: 'nguoi-di-rung',
    databaseURL: 'https://nguoi-di-rung-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nguoi-di-rung.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8cBpxR6yV9wzvqyu7xy1FWgrkyeYO0BE',
    appId: '1:951154714575:ios:36a470d97a258a627294ba',
    messagingSenderId: '951154714575',
    projectId: 'nguoi-di-rung',
    databaseURL: 'https://nguoi-di-rung-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nguoi-di-rung.firebasestorage.app',
    iosBundleId: 'com.example.projectProjectck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8cBpxR6yV9wzvqyu7xy1FWgrkyeYO0BE',
    appId: '1:951154714575:ios:36a470d97a258a627294ba',
    messagingSenderId: '951154714575',
    projectId: 'nguoi-di-rung',
    databaseURL: 'https://nguoi-di-rung-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nguoi-di-rung.firebasestorage.app',
    iosBundleId: 'com.example.projectProjectck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoyA5GpUoVVi1VBkVda-TIlcytjNrqX6Q',
    appId: '1:951154714575:web:9530dea658f385377294ba',
    messagingSenderId: '951154714575',
    projectId: 'nguoi-di-rung',
    authDomain: 'nguoi-di-rung.firebaseapp.com',
    databaseURL: 'https://nguoi-di-rung-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nguoi-di-rung.firebasestorage.app',
    measurementId: 'G-GQP6RZF5HW',
  );
}
